version: '3'

services:
    nginx:
        build:
            context: ./dockerfiles
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./html:/var/www/html
        depends_on:
            - php
            - mysql
        command: >
            sh -c 'until nc -z mysql 3306; do sleep 1; done; nginx -g "daemon off;"'
    
    mysql:
        image: mysql:latest
        volumes:
            - ./data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydatabase
        command: --init-file /docker-entrypoint-initdb.d/init.sql

    php:
        build:
            context: ./dockerfiles
            dockerfile: Dockerfile.php
        ports:
            - "9000:9000"
        volumes:
            - ./html:/var/www/html
        depends_on:
            - mysql

volumes:
    data: